['Bigtex20'] = { -- This has to match the spawn code of the vehicle
    ['name'] = 'BigTex 20ft', -- This is the display of the vehicle
    ['brand'] = 'Trailor', -- This is the vehicle's brand (Ford, Chevrolet, BMW, Mercedes, etc)
    ['model'] = 'Bigtex20', -- This must match the spawn code of the vehicle
    ['price'] = 1000000, -- The price that the vehicle sells for
    ['category'] = 'imports', -- This must match 'VehicleClass' in vehicles.meta 
    ['categoryLabel'] = 'Imports', -- Customize for your Vehicle Shop headings (can even include spaces)
    ['hash'] = `Bigtex20`, -- This has to match the spawn code of the vehicle and must be surrounded by backticks. Example of a Backtick: `
    ['shop'] = 'pdm', -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
},
['ehauler'] = { -- This has to match the spawn code of the vehicle
    ['name'] = 'Inclosed 30ft', -- This is the display of the vehicle
    ['brand'] = 'Trailor', -- This is the vehicle's brand (Ford, Chevrolet, BMW, Mercedes, etc)
    ['model'] = 'ehauler', -- This must match the spawn code of the vehicle
    ['price'] = 1000000, -- The price that the vehicle sells for
    ['category'] = 'imports', -- This must match 'VehicleClass' in vehicles.meta 
    ['categoryLabel'] = 'Imports', -- Customize for your Vehicle Shop headings (can even include spaces)
    ['hash'] = `ehauler`, -- This has to match the spawn code of the vehicle and must be surrounded by backticks. Example of a Backtick: `
    ['shop'] = 'pdm', -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
},
['enclosedgoose'] = { -- This has to match the spawn code of the vehicle
    ['name'] = '30ft gooseneck', -- This is the display of the vehicle
    ['brand'] = 'Trailor', -- This is the vehicle's brand (Ford, Chevrolet, BMW, Mercedes, etc)
    ['model'] = 'enclosedgoose', -- This must match the spawn code of the vehicle
    ['price'] = 1000000, -- The price that the vehicle sells for
    ['category'] = 'imports', -- This must match 'VehicleClass' in vehicles.meta 
    ['categoryLabel'] = 'Imports', -- Customize for your Vehicle Shop headings (can even include spaces)
    ['hash'] = `enclosedgoose`, -- This has to match the spawn code of the vehicle and must be surrounded by backticks. Example of a Backtick: `
    ['shop'] = 'pdm', -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
},['thauler'] = { -- This has to match the spawn code of the vehicle
    ['name'] = '20ft pullbahind ', -- This is the display of the vehicle
    ['brand'] = 'Trailor', -- This is the vehicle's brand (Ford, Chevrolet, BMW, Mercedes, etc)
    ['model'] = 'thauler', -- This must match the spawn code of the vehicle
    ['price'] = 1000000, -- The price that the vehicle sells for
    ['category'] = 'imports', -- This must match 'VehicleClass' in vehicles.meta 
    ['categoryLabel'] = 'Imports', -- Customize for your Vehicle Shop headings (can even include spaces)
    ['hash'] = `thauler`, -- This has to match the spawn code of the vehicle and must be surrounded by backticks. Example of a Backtick: `
    ['shop'] = 'pdm', -- Can be a single shop or multiple shops. For multiple shops for example {'shopname1','shopname2','shopname3'}
},